project_name: boyc-project

s3:
  bucket_name: sagemaker-us-east-1-488578253112
  data_prefix: data
  model_prefix: models
  inference_prefix: inference

data:
  training: training/data.csv
  validation: validation/data.csv
  test: test/data.csv

models:
  model_name: boyc-trainable-mode-model

inference:
  batch1: inference/batch1/
  batch2: inference/batch2/
  # Adicione outros lotes conforme necessário

sagemaker:
  instance_type: ml.m5.large
  initial_instance_count: 1
  max_runtime_in_seconds: 3600
  model_package_group_name: boyc-project-model
  approval_status: PendingManualApproval
  inference_instance_type: ml.m5.large
  inference_initial_instance_count: 1

training:
  enable_training: true  # Defina como true para modelos treináveis
  training_job_name_prefix: boyc-training-job
  instance_type: ml.m5.large
  instance_count: 1
  max_runtime_in_seconds: 86400
  output_path: models/boyc-trainable-mode-model/output/
  hyper_parameters:  # Hiperparâmetros do modelo
    batch_size: 32
    learning_rate: 0.001
    epochs: 10
  input_data_config:
    training_data: data/training/
    validation_data: data/validation/

monitoring:
  enable_model_monitoring: true
  baseline_job_name: boyc-model-monitoring-baseline-job
  monitoring_schedule_name: boyc-model-monitoring-schedule
  monitoring_output_config:
    s3_output_path: s3://bucket-test/boyc-project/monitoring-output/
  schedule_config:
    schedule_expression: "cron(0 * ? * * *)"  # Executa a cada hora
  monitoring_resources:
    cluster_config:
      instance_count: 1
      instance_type: ml.m5.large
      volume_size_in_gb: 20
  endpoint_input:
    endpoint_name: boyc-inference-mode-endpoint
    local_path: /opt/ml/processing/input
  constraints_resource:
    s3_uri: s3://bucket-test/boyc-project/monitoring-constraints/
  statistics_resource:
    s3_uri: s3://bucket-test/boyc-project/monitoring-statistics/
