model_type: "trainable"  # Pode ser "trainable" ou "pre-trained"
model_name_prefix: "boyc-inference-mode-model"
endpoint_config_name_prefix: "boyc-inference-mode-config"
endpoint_name_prefix: "boyc-inference-mode"

inference:
  InstanceType: "ml.m5.large"
  InitialInstanceCount: 1
  ModelDataUrl: "" 

training:
  EnableTraining: true  # Defina como true para modelos treináveis
  TrainingJobNamePrefix: "boyc-training-job"
  InstanceType: "ml.m5.large"
  InstanceCount: 1
  MaxRuntimeInSeconds: 86400
  OutputPath: "sagemaker-us-east-1-488578253112/training-output/"
  HyperParameters:  # Hiperparâmetros do modelo
    batch_size: 32
    learning_rate: 0.001
    epochs: 10
  InputDataConfig:
    TrainingData: "sagemaker-us-east-1-488578253112/training-data/"
    ValidationData: "sagemaker-us-east-1-488578253112/validation-data/"

s3:
  input_bucket: "sagemaker-us-east-1-488578253112/training-data"
  output_bucket: "sagemaker-us-east-1-488578253112/training-output"
  data_prefix: "data.csv"

# Configurações de monitoramento e logs
monitoring:
  EnableModelMonitoring: true
  BaselineJobName: "boyc-model-monitoring-baseline-job"
  MonitoringScheduleName: "boyc-model-monitoring-schedule"
  MonitoringOutputConfig:
    S3OutputPath: "s3://your-output-bucket/monitoring-output/"
  ScheduleConfig:
    ScheduleExpression: "cron(0 * ? * * *)"  # Executa a cada hora
  MonitoringResources:
    ClusterConfig:
      InstanceCount: 1
      InstanceType: "ml.m5.large"
      VolumeSizeInGB: 20
  EndpointInput:
    EndpointName: "boyc-inference-mode-endpoint"
    LocalPath: "/opt/ml/processing/input"
  ConstraintsResource:
    S3Uri: "s3://your-output-bucket/monitoring-constraints/"
  StatisticsResource:
    S3Uri: "s3://your-output-bucket/monitoring-statistics/"
